### ISSUE TITLE
Parameter order error while initializing Proccess

### ISSUE THREAD

**Issue by liugan-github** [riltech/stream#1]
// NewProcess creates a new process able to spawn transcoding FFMPEG processes
func NewProcess(
	keepFiles bool,
	audio bool,
	loggingOpts ProcessLoggingOpts,
) *Process {
	return &Process{audio, keepFiles, loggingOpts}
}

The right one is &Process{keepFiles,audio,  loggingOpts}

**Comment by Roverr** [comment]
@liugan-github Very nice catch, thank you! I'll release a new version today
