### ISSUE TITLE
Process.loggingOpts is unused inside Process

### ISSUE THREAD

**Issue by aldas** [riltech/stream#3]
Process struct contains ProcessLoggingOpts as loggingOpts member  but it is not used anywhere. insided Process. "loggingOpts" is private so you can not even access it out of this library package if would want to access it. 

Maybe conceptually ProcessLoggingOpts belong only to Stream and Process itself should not know about it.

**Comment by Roverr** [comment]
Hi @aldas ,

Fair point, I'm preparing a fix to remove it. The process itself should not know about the wrapping logging options.

Great catch, thank you!
